### ISSUE TITLE
V2 Roadmap

### ISSUE THREAD

**Issue by jdecool** [jdecool/TwigConstantAccessorBundle#37]
The version 2 of this bundle is a complete rewrite.

- Should not based on Symfony DIC
- Avoid to create a service for the object

Functional requirements:

- [x] Declare class (existing feature)
- [x] Allow aliasing (existing feature)
- [x] Get accessible constants through regex (existing feature)
- [ ] Allow class to be accessible through `AsTwigConstantAccessor` attribute (existing feature)
- [ ] Allow to parse files using a regex
- [ ] Load class constants using a namespace
